# Generated by Django 4.1.6 on 2023-02-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='img',
        ),
        migrations.AddField(
            model_name='chat',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
