# Generated by Django 4.1.6 on 2023-02-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_img_chat_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='img_url',
        ),
    ]
